scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser
    min_x: -2.5
    max_x: 2.5
    min_y: -2.5
    max_y: 2.5
    min_z: -0.1
    max_z: 0.1
    invert: true

- name: dark_shadows
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 100
    upper_threshold: 10000
    disp_histogram: 0