DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 1000
    BATCH_SIZE: 16
    CROP_SIZE: (256, 256)
TEST:
    BATCH_SIZE:   8
    TEST_MODEL_PATH: 'checkpoints/best_model.pth'   
    ##'checkpoints/fast_scnn_segmentron.pth'
##TEST_MODEL_PATH: 'checkpoints/best_model.pth'

SOLVER:
    LR: 0.045
    DECODER_LR_FACTOR: 1.0
    WEIGHT_DECAY: 4e-5
    AUX: True
    AUX_WEIGHT: 0.4

AUG:
    COLOR_JITTER: 0.4

MODEL:
    MODEL_NAME: "FastSCNN"
    BN_MOMENTUM: 0.01
